# Generated by Django 4.0.4 on 2022-09-30 00:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=80, verbose_name='Título')),
                ('sub_name', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('content', ckeditor.fields.RichTextField(max_length=5000, verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('photo', models.ImageField(default='media/images/no_image.jpg', null=True, upload_to='posts', verbose_name='Foto')),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Science Fiction', 'Science Fiction'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('Shounen', 'Shounen'), ('Fantasy', 'Fantasy')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=64, verbose_name='Nombre')),
                ('content', models.TextField(max_length=300, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AppBlog.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
