# Generated by Django 4.0.4 on 2022-10-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='D:/Documents/App_Blog/media/images/no_image.jpg', null=True, upload_to='D:/Documents/App_Blog/media/images/', verbose_name='Foto'),
        ),
    ]
