# Generated by Django 4.0.4 on 2022-10-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/no_image.jpg', null=True, upload_to='images/', verbose_name='Foto'),
        ),
    ]
