# Generated by Django 4.0.4 on 2022-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fiction', 'Fiction'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('Shounen', 'Shounen'), ('Fantasy', 'Fantasy')], max_length=20),
        ),
    ]
