# Generated by Django 4.0.4 on 2022-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
